name: Mobile CI

on:
  push:
    branches: [ "main", "Front-Dev" ]
    paths:
      - 'mobile/**'
  pull_request:
    branches: [ "main", "Front-Dev" ]
    paths:
      - 'mobile/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile

    steps:
    - uses: actions/checkout@v4
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: Install dependencies
      run: flutter pub get
    - name: Analyze
      run: flutter analyze
    # Note: Uncomment below if you have tests
    # - name: Run tests
    #   run: flutter test
